version: '3.3'
services:
  solr1:
    container_name: solr1
    image: mhzed/solr-disjoin
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - "8981:8983"
    #volumes:
    #  - ./data/solr1:/opt/solr/server/solr
    #  - ./solr.xml:/opt/solr/server/solr/solr.xml
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr

  solr2:
    image: mhzed/solr-disjoin
    container_name: solr2
    ports:
     - "8982:8983"
    #volumes:
    #  - ./data/solr2:/opt/solr/server/solr
    #  - ./solr.xml:/opt/solr/server/solr/solr.xml
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    entrypoint:
      - docker-entrypoint.sh
      - solr
      - start
      - -f
      - -c
      - -z
      - zoo1:2181,zoo2:2181,zoo3:2181
      - -a
      - "-Xdebug -Xrunjdwp:transport=dt_socket,server=y,suspend=n,address=1044"
    networks:
      - solr

  zoo1:
    image: zookeeper
    container_name: zoo1
    restart: always
    hostname: zoo1
    volumes:
      - ./data/zoo1/data:/data
      - ./data/zoo1/datalog:/datalog    
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo2:
    image: zookeeper
    container_name: zoo2
    restart: always
    hostname: zoo2
    volumes:
      - ./data/zoo2/data:/data
      - ./data/zoo2/datalog:/datalog        
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

  zoo3:
    image: zookeeper
    container_name: zoo3
    restart: always
    hostname: zoo3
    volumes:
      - ./data/zoo3/data:/data
      - ./data/zoo3/datalog:/datalog        
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
    networks:
      - solr

networks:
  solr: